site_name: e-SUS AF - Documentação Negocial

dev_addr: 127.0.0.1:8005

nav:
  - Home: index.md
  - Especificações Técnicas: 
    - Documento de Mensagens: EspecificacoesTecnicas/DocumentoDeMensagens.md
    - Documento de Regras: EspecificacoesTecnicas/DocumentoDeRegras.md
    - ETE001 - Cadastro e login: EspecificacoesTecnicas/ETE001.md
    - ETE017 - Cadastrar Entrada: EspecificacoesTecnicas/ETE017.md
  - Histórias de Usuário:
    - Documento de Mensagens: HistoriasDeUsuario/Documento de Mensagens.md
    - Documento de Regras: HistoriasDeUsuario/Documento de Regras.md
    - HU001 - Cadastro e Login: HistoriasDeUsuario/HU001.md
    - HU004 - Solicitar Acesso: HistoriasDeUsuario/HU004.md
    - HU016 - Consultar Entrada: HistoriasDeUsuario/HU016.md
    - HU017 - Cadastrar Entrada: HistoriasDeUsuario/HU017.md
  - Casos de Teste:
    - CT004 - Solicitar Uma Permissão de acesso: CasosDeTeste/CT004.md
  - Sobre: sobre.md

theme: readthedocs
