site_name: e-SUS AF - Documentação Negocial

dev_addr: 127.0.0.1:8005

nav:
  - Home: index.md
  - Especificações Técnicas: 
    - Documento de Mensagens: EspecificacoesTecnicas/DocumentoDeMensagensv2.md
    - Documento de Regras: EspecificacoesTecnicas/DocumentoDeRegrasv2.md
#    - ETE001 - Cadastro e login: EspecificacoesTecnicas/ETE001.md
    - ETE012 - Consultar Estabelecimento: EspecificacoesTecnicas/ETE012.md
    - ETE013 - Cadastrar Estabelecimento: EspecificacoesTecnicas/ETE013.md
    - ETE014 - Editar Estabelecimento: EspecificacoesTecnicas/ETE014.md
    - ETE015 - Detalhar Estabelecimento: EspecificacoesTecnicas/ETE015.md
    - ETE019 - Consultar Entrada: EspecificacoesTecnicas/ETE019.md
    - ETE020 - Cadastrar Entrada: EspecificacoesTecnicas/ETE020.md
    - ETE021 - Editar Entrada: EspecificacoesTecnicas/ETE021.md
    - ETE022 - Detalhar Entrada: EspecificacoesTecnicas/ETE022.md
#    - ETE023 - : EspecificacoesTecnicas/ETE023.md
    - ETE024 - Consultar Saída Diversa: EspecificacoesTecnicas/ETE024.md
    - ETE025 - Cadastrar Saída Diversa: EspecificacoesTecnicas/ETE025.md
    - ETE026 - Editar Saída Diversa: EspecificacoesTecnicas/ETE026.md
    - ETE027 - Detalhar Saída Diversa: EspecificacoesTecnicas/ETE027.md
#  - Histórias de Usuário:
#    - HU001 - Cadastro e Login: HistoriasDeUsuario/HU001.md
#    - HU004 - Solicitar Acesso: HistoriasDeUsuario/HU004.md
#    - HU016 - Consultar Entrada: HistoriasDeUsuario/HU016.md
#    - HU017 - Cadastrar Entrada: HistoriasDeUsuario/HU017.md
#  - Casos de Teste:
#    - CT004 - Solicitar Uma Permissão de acesso: CasosDeTeste/CT004.md
  - Sobre: sobre.md

theme: readthedocs
