site_name: e-SUS AF - Documentação Negocial

dev_addr: 127.0.0.1:8005

nav:
  - Home: index.md
  - Especificações Técnicas:
    - Documento de Mensagens: EspecificacoesTecnicas/DocumentoDeMensagensv2.md
    - Documento de Regras: EspecificacoesTecnicas/DocumentoDeRegrasv2.md
    - Especificações:
      - ETE001 - Realizar Login: EspecificacoesTecnicas/ETE001.md
      - ETE002 - Cadastrar Usuário do Sistema: EspecificacoesTecnicas/ETE002.md
      - ETE003 - Recuperar Senha: EspecificacoesTecnicas/ETE003.md
      - ETE004 - Consultar Permissões de Acesso: EspecificacoesTecnicas/ETE004.md
      - ETE005 - Atribuir Perfil de Acesso: EspecificacoesTecnicas/ETE005.md
      - ETE006 - Detalhar Permissão de Acesso: EspecificacoesTecnicas/ETE006.md
      - ETE007 - Consultar Meus Perfis: EspecificacoesTecnicas/ETE007.md
      - ETE008 - Solicitar Perfil: EspecificacoesTecnicas/ETE008.md
      - ETE009 - Detalhar Meu Perfil : EspecificacoesTecnicas/ETE009.md
      - ETE010 - Consultar Perfil : EspecificacoesTecnicas/ETE010.md
      - ETE011 - Cadastrar Perfil : EspecificacoesTecnicas/ETE011.md
      - ETE012 - Detalhar Perfil : EspecificacoesTecnicas/ETE012.md
      - ETE013 - Consultar Entes : EspecificacoesTecnicas/ETE013.md
      - ETE014 - Cadastrar Ente : EspecificacoesTecnicas/ETE014.md
      - ETE015 - Consultar Estabelecimento: EspecificacoesTecnicas/ETE015.md
      - ETE016 - Cadastrar Estabelecimento: EspecificacoesTecnicas/ETE016.md
      - ETE017 - Editar Estabelecimento: EspecificacoesTecnicas/ETE017.md
      - ETE018 - Detalhar Estabelecimento: EspecificacoesTecnicas/ETE018.md
      - ETE019 - Consultar Entrada: EspecificacoesTecnicas/ETE019.md
      - ETE020 - Cadastrar Entrada: EspecificacoesTecnicas/ETE020.md
      - ETE021 - Editar Entrada: EspecificacoesTecnicas/ETE021.md
      - ETE022 - Detalhar Entrada: EspecificacoesTecnicas/ETE022.md
      - ETE023 - Consultar Saída: EspecificacoesTecnicas/ETE023.md
      - ETE024 - Cadastrar Saída: EspecificacoesTecnicas/ETE024.md
      - ETE025 - Editar Saída: EspecificacoesTecnicas/ETE025.md
      - ETE026 - Detalhar Saída: EspecificacoesTecnicas/ETE026.md
      - ETE027 - Emitir Relatório de Posição de Estoque: EspecificacoesTecnicas/ETE027.md
      - ETE028 - Detalhar Relatório de Posição de Estoque : EspecificacoesTecnicas/ETE028.md
      - ETE029 - Consultar Usuário SUS: EspecificacoesTecnicas/ETE029.md
      - ETE030 - Cadastrar Usuário SUS: EspecificacoesTecnicas/ETE030.md
      - ETE031 - Editar Usuário SUS: EspecificacoesTecnicas/ETE031.md
      - ETE032 - Detalhar Usuário SUS: EspecificacoesTecnicas/ETE032.md
      - ETE033 - Gestão de Integrações: EspecificacoesTecnicas/ETE033.md
      - ETE034 - Configurar Integração Barramento AF: EspecificacoesTecnicas/ETE034.md
      - ETE035 - Detalhar Integração Barramento AF: EspecificacoesTecnicas/ETE035.md
      - ETE036 - Atualizar Dados Cadastrais de Integração Barramento AF: EspecificacoesTecnicas/ETE036.md
      - ETE037 - Gestão de Estoques: EspecificacoesTecnicas/ETE037.md
      - ETE038 - Autenticação com GOV.BR: EspecificacoesTecnicas/ETE038.md
      - ETE039 - Transferência de Produtos entre Estabelecimentos: EspecificacoesTecnicas/ETE039.md
      - ETE040 - Requisição de produtos para estabelecimentos: EspecificacoesTecnicas/ETE040.md
      - ETE041 - Configurar transmissão SI Bnafar: EspecificacoesTecnicas/ETE041.md
      - ETE042 - Transmitir dados SI Bnafar: EspecificacoesTecnicas/ETE042.md
      - ETE043 - Visualizar transmissão federal: EspecificacoesTecnicas/ETE043.md
    - Para Validação:
      - ETE - Gerenciar Perfil : validacao/ETE-gerenciar-perfil.md
      - ETE005 - Atribuir Permissão de Acesso : validacao/ETE005.md
      - ETE014 - Adicionar um ente / instituição ao e-SUS AF : validacao/ETE014.md
      - ETE023 - Consultar Saídas : validacao/ete023.md
      - ETE024 - Cadastrar Saídas : validacao/ete024.md
      - ETE025 - Editar Saídas : validacao/ete025.md
      - ETE026 - Detalhar Saídas : validacao/ete026.md
      - ETE029 - Estornar Saída : validacao/ete029.md
      - ETE040 - Cadastro de Entes : validacao/ETE041_dev.md


#  - Histórias de Usuário:
#    - HU001 - Cadastro e Login: HistoriasDeUsuario/HU001.md
#    - HU004 - Solicitar Acesso: HistoriasDeUsuario/HU004.md
#    - HU016 - Consultar Entrada: HistoriasDeUsuario/HU016.md
#    - HU017 - Cadastrar Entrada: HistoriasDeUsuario/HU017.md
#  - Casos de Teste:
#    - CT004 - Solicitar Uma Permissão de acesso: CasosDeTeste/CT004.md
  # - Sobre: sobre.md

theme: readthedocs

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tilde
  - admonition

plugins:
  - search
  - mermaid2
